# -*- coding: utf-8 -*-
"""buku

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12EEVPcC-tKiHOFVmBHgJCPrH106SdHWa
"""

class Buku:
    def __init__(self, judul, penulis):
        self.judul = judul
        self.penulis = penulis

    def info_buku(self):
        print(f"Buku berjudul '{self.judul}' ditulis oleh {self.penulis}.")

# Objek
book = Buku("Laskar Pelangi", "Andrea Hirata")
book.info_buku()