# -*- coding: utf-8 -*-
"""Mahasiswa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zFrNHmcfw52VhKblNBs_livXNY9Gx41A
"""

class Mahasiswa:
    def __init__(self, nama, nim):
        self.nama = nama
        self.nim = nim

    def cetak_krs(self):
        print(f"Mahasiswa {self.nama} dengan NIM {self.nim} telah mencetak KRS.")

# Objek
mhs = Mahasiswa("Sonia Sabira Gayoara", "220705033")
mhs.cetak_krs()