# -*- coding: utf-8 -*-
"""mobil

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13yEtxYOds5uL72reFO96hF2nZfg3kZv5
"""

class Mobil:
    def __init__(self, merk, warna):
        self.merk = merk
        self.warna = warna

    def info_mobil(self):
        print(f"Mobil {self.merk} berwarna {self.warna} siap digunakan.")

# Objek
car = Mobil("Toyota", "Merah")
car.info_mobil()